run_name: wikidiverse
seed: 42
code_path: "/home/xxx/code/mel/rcmel-my/"
llm: "/home/xxx/code/models/Llama-3.1-8B-Instruct"
mllm: "/home/xxx/code/models/llava-v1.6-mistral-7b-hf"
embedding_model: "/home/xxx/code/models/SFR-Embedding-Mistral"

ent:
  entity_data_dir: "data/wikidiverse/kb_entity_filtered.json"
  entity_image_dir: "data/wikidiverse/kb_image/"

  # 实体增强step by step
  entity_output_dir_mllm: "data/wikidiverse/kb_entity_filtered_desc_mllm.json"
  entity_output_dir_mllm_llm: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm.json"

mention:
  mention_data_dir: "data/wikidiverse/wikidiverse_test_1.json"
  mention_image_dir: "data/wikidiverse/mention_image/"
  # 提及增强多卡多步
  mention_output_dir_mllm: "data/wikidiverse/wikidiverse_test_1_mllm.json"
  mention_output_dir_mllm_llm: "data/wikidiverse/wikidiverse_test_1_mllm_llm.json"

embed:
  max_length: 4096
  top_k: 30
  entity_embedding_dir: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm.json"
  entity_embedding_output_dir: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm_embedding.pt"

  mention_embedding_dir: "data/wikidiverse/wikidiverse_test_1_mllm_llm_embedding.json"
  mention_embedding_output_dir: "data/wikidiverse/wikidiverse_test_1_mllm_llm_embedding.json"

  
top:
  mention_rank_output_dir: "data/wikidiverse/wikidiverse_test_1_mllm_llm_embedding_rank.json"
  entity_dir: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm.json"
  entity_embed_name: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm_embedding_name.pt"
  entity_embed_name_desc: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm_embedding_name_desc.pt"

infer_kc:
  mention_rank_input_dir: "data/wikidiverse/wikidiverse_test_1_mllm_llm_embedding_rank.json"
  entity_desc_llm_mllm_dir: "data/wikidiverse/kb_entity_filtered_desc_mllm_llm.json"
  mention_infer_kc: "data/wikidiverse/wikidiverse_test_1_mllm_llm_embedding_rank_kc.json"

decoding:
  mention_entity_diff_dir: "data/wikidiverse/wikidiverse_test_1_mllm_llm_embedding_rank_kc.json" 
  result: "data/wikidiverse/result.json"
  m: 30