dataset="wikidiverse"
# python main_entity.py "$dataset"
# python main_mention.py "$dataset"
# python main_top.py "$dataset"
# python main_infer.py "$dataset"
python main_decoding.py "$dataset"
# python metric.py "$dataset"